-- ============================================================
-- Q6: Revenue Impact of the Gsearch Lander-1 A/B Test
-- ------------------------------------------------------------
-- Business Question:
--   Could you estimate the revenue generated by the lander-1
--   test? We want to know if the new landing page is actually
--   driving more orders than the original /home page.
-- ------------------------------------------------------------
-- Tables Used : website_pageviews, website_sessions, orders
-- Test Period : After first /lander-1 pageview (id: 23504)
--               Before 2012-07-28
-- ============================================================

USE mavenfuzzyfactory;

-- STEP 1: Find the first pageview_id that saw /lander-1
SELECT 
    MIN(website_pageview_id) AS first_test_pageview
FROM website_pageviews 
WHERE pageview_url = '/lander-1';
-- Result: 23504

-- STEP 2 & 3: Get session-level landing page data
WITH first_pageview_session AS (
    SELECT 
        wp.website_session_id,
        MIN(wp.website_pageview_id) AS min_pageview_id
    FROM website_pageviews wp
        INNER JOIN website_sessions ws USING (website_session_id)
    WHERE ws.created_at < '2012-07-28'
      AND wp.website_pageview_id >= 23504
      AND utm_source = 'gsearch'
      AND utm_campaign = 'nonbrand'
    GROUP BY 1
),
session_landing_page AS (
    SELECT 
        fps.website_session_id,
        wp.pageview_url AS landing_page
    FROM first_pageview_session fps
        LEFT JOIN website_pageviews wp ON wp.website_pageview_id = fps.min_pageview_id
    WHERE wp.pageview_url IN ('/home', '/lander-1')
),
session_orders AS (
    SELECT 
        slp.website_session_id,
        slp.landing_page, 
        o.order_id
    FROM session_landing_page slp
        LEFT JOIN orders o USING (website_session_id)
)

-- STEP 4: Compare conversion rates between the two landing pages
SELECT 
    landing_page, 
    COUNT(DISTINCT website_session_id) AS sessions, 
    COUNT(DISTINCT order_id)           AS orders,
    COUNT(DISTINCT order_id)
        / COUNT(DISTINCT website_session_id) AS conversion_rate
FROM session_orders
GROUP BY 1;

-- ------------------------------------------------------------
-- STEP 5: Calculate incremental revenue from the test
-- ------------------------------------------------------------
-- Find the last session that was sent to /home before the test ended
SELECT 
    MAX(ws.website_session_id) AS last_home_session
FROM website_pageviews wp 
    LEFT JOIN website_sessions ws USING (website_session_id)
WHERE utm_source = 'gsearch'
  AND utm_campaign = 'nonbrand'
  AND pageview_url = '/home'
  AND ws.created_at < '2012-11-27';
-- Result: session_id 17145

-- Count sessions since the test ended (sent to lander-1 only)
SELECT 
    COUNT(DISTINCT website_session_id) AS sessions_since_test
FROM website_sessions
WHERE utm_source = 'gsearch'
  AND utm_campaign = 'nonbrand'
  AND created_at < '2012-11-27'
  AND website_session_id > 17145;
-- Result: 22,972 sessions

-- ------------------------------------------------------------
-- Revenue Calculation:
--   Lander-1 CVR:  ~8.7%  |  Home CVR: ~5.8%
--   Incremental CVR lift: 0.87 percentage points
--   22,972 sessions x 0.0087 = ~202 incremental orders
--   ~202 orders over ~4 months = ~50 extra orders per month
-- ------------------------------------------------------------
